update deps.
"cargo audit" was showing a vulnerability in tar 0.4.15, this updates to tar v0.4.16.

error: Vulnerable crates found!
ID:  RUSTSEC-2018-0002
Crate:   tar
Version: 0.4.15
Date:    2018-06-29
URL:     https://github.com/alexcrichton/tar-rs/pull/156
Title:   Links in archives can overwrite any existing file
Solution: upgrade to: >= 0.4.16
error: 1 vulnerability found!